# Generated by Django 4.2.7 on 2024-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
