# Generated by Django 4.2.4 on 2023-11-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='original_url',
            new_name='link',
        ),
    ]
