# Generated by Django 4.2.7 on 2024-01-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0002_shorturl_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='redirect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
