# Generated by Django 4.2.7 on 2023-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0002_rename_original_url_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=700)),
                ('short_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
