# Generated by Django 4.2.7 on 2024-01-19 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0003_shorturl_redirect_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
