FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /usr/src/project_shorterner

RUN apt-get update \
  && apt-get install -y --no-install-recommends postgresql-client libpq-dev gcc \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY ./requirements.txt usr/src/requirements.txt

RUN pip install -r usr/src/requirements.txt

COPY . /usr/src/project_shorterner

EXPOSE 8000

#CMD ["python", "manage.py", "runserver", "127.0.0.1:8000"]


