version: '3.9'

services:
  db:
    image: postgres:16
    container_name: shorterner_postgres
    volumes:
      - postgres_data:/var/src/lib/postgresql/data/
    env_file:
      - .env
      

  project_shorterner:
    build: .
    container_name: shorterner_project
    command: python /usr/src/project_shorterner/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/project_shorterner
    ports:
      - 8000:8000
volumes:
  postgres_data: